# Mundo 6

In [6]:
import numpy as np

In [7]:
#todas as operações funcionam com os vetores.

array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 2])

lista_normal = [1, 1, 1, 1]
lista_normal2 = [4, 2, 6, 2]

print(array1 + array2)
print(lista_normal + lista_normal2)

[5 3 7 3]
[1, 1, 1, 1, 4, 2, 6, 2]


In [8]:
print(array1 + array3) #couldnt ada because the vetors ahve different sizes

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
#E se eu quiser somar um número só?

soma_a_todos_os_elementos = np.array([1, 1, 1, 1]) + 20

print(soma_a_todos_os_elementos)

[21 21 21 21]


In [ ]:
#todas as operações funcionam normal
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])

subtracao = array1 - array2
divisao = array1/array2
multiplicacao = array1 * array2
exponenciacao = array1 ** array2

print(subtracao)
print(divisao)
print(multiplicacao)
print(exponenciacao)

[-3 -1 -5 -1]
[0.25       0.5        0.16666667 0.5       ]
[4 2 6 2]
[1 1 1 1]


In [ ]:
#Operações dentro do próprio vetor

vetor = np.array([1, 4, -4, -1, 2])

print(vetor)
print(vetor.sum())
print(vetor.max())
print(vetor.min())
print(np.abs(vetor)) #Calcula os valores absolutos

[ 1  4 -4 -1  2]
2
4
-4
[1 4 4 1 2]


In [ ]:
#Estatisticas descritivas

vetor = np.array([1, 20, -4, -12, 2000])

media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)

print(media) #media
print(mediana) #mediana
print(desvio_p) #desvio padrao
print(var) #variancia

401.0
1.0
799.56938410622
639311.2


In [ ]:
#matriz de correlação 

vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

correlacao = np.corrcoef((vetor, vetor2, vetor3))

correlacao

array([[ 1.        ,  0.25471058, -0.13247913],
       [ 0.25471058,  1.        ,  0.76783876],
       [-0.13247913,  0.76783876,  1.        ]])

# Exercício

* Exercício 35: Faça um programa que o usuário digite a rentabilidade de ações, com quantas ações o usuário quiser. Transforme essas listas em arrays e devolva pro usuário:

        A média de rentabilidade da carteira.
        O Desvio padrão da carteira.
        A mediana de retornos da carteira.
        O maior retorno.
        O menor retorno.

In [7]:
import numpy as np

arrays_rentabilidade = np.array([])  # Criando um array vazio.

while True:
    try:
        rentabilidade = float(input("Digite uma rentabilidade: "))
        arrays_rentabilidade = np.append(arrays_rentabilidade, rentabilidade)  # Adiciona ao array
    except ValueError:
        print("Erro! Digite um número válido.")
        continue  # Volta para o início do loop

    # Loop para garantir que o usuário só digite 'S' ou 'N'
    while True:
        continuar = input("Deseja cadastrar mais rentabilidades? [S/N] ").strip().upper()
        if continuar in ['S', 'N']:
            break  # Sai do loop se for uma entrada válida
        print("Entrada inválida! Digite apenas 'S' ou 'N'.")

    if continuar == 'N':
        break  # Encerra o loop principal

# Verifica se há valores antes de calcular estatísticas
if arrays_rentabilidade.size > 0:
    print(f'A média é: {np.mean(arrays_rentabilidade)}, a mediana é: {np.median(arrays_rentabilidade)}, '
          f'o mínimo é: {np.min(arrays_rentabilidade)}, o máximo é: {np.max(arrays_rentabilidade)}, '
          f'e o DP é: {np.std(arrays_rentabilidade)}')
else:
    print("Nenhuma rentabilidade cadastrada. Não há estatísticas para exibir.")


Digite uma rentabilidade: 30
Deseja cadastrar mais rentabilidades? [S/N] 30
Entrada inválida! Digite apenas 'S' ou 'N'.
Deseja cadastrar mais rentabilidades? [S/N] S
Digite uma rentabilidade: 50
Deseja cadastrar mais rentabilidades? [S/N] 60
Entrada inválida! Digite apenas 'S' ou 'N'.
Deseja cadastrar mais rentabilidades? [S/N] N
A média é: 40.0, a mediana é: 40.0, o mínimo é: 30.0, o máximo é: 50.0, e o DP é: 10.0


# Galáxia 4

Fim do módulo do Numpy! Na galáxia 4 nós iremos abordar o módulo Pandas, a principal biblioteca de análise de dados que existe.
Vamos aprender a puxar cotações, criar médias móveis, tratar dados, ler planilhas de excel e muito mais. Te vejo lá!