# Mundo 4

In [ ]:
import numpy as np

In [ ]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

vetor2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
#posições

print(vetor[0])

print(vetor[0:2])

print(vetor[-1])

print(vetor2d[2][0])
print(vetor2d[0][1])

1
[1 2]
9
7
2


In [ ]:
#filtrando dados

vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

maior_que_5 = vetor[vetor > 5]

somente_par = vetor[vetor % 2 == 0]

igual_a_5 = vetor[vetor == 5]

maior_que_3_menor_que_8 = vetor[ (vetor > 5) & (vetor < 8)] 

print(maior_que_5)
print(somente_par)
print(igual_a_5)
print(maior_que_3_menor_que_8)

[6 7 8 9]
[2 4 6 8]
[5]
[6 7]


# Exercício

* Exercício 33: Faça um programa que gere um vetor de retornos positivos ou negativos entre -1 e 1 na quantidade de dias que o usuário escolher. Devolva um vetor dos retornos positivos, o primeiro e o último retorno.

In [20]:
import numpy as np

dias = int(input('Quantos retornos de dias devem ser gerados? '))

retorno_aleatório = np.random.uniform(-1,1,dias)

nup_positivos = retorno_aleatório[retorno_aleatório > 0]
nup_negativos = retorno_aleatório[retorno_aleatório < 0]

print(nup_positivos)
print(nup_negativos)

print(f'o primeiro retorno é {nup_positivos[0]} e o ultimo é {nup_positivos[-1]}')

Quantos retornos de dias devem ser gerados? 5
[ 0.025289    0.19361542  0.65131391]
[-0.83614778 -0.51814872]
o primeiro retorno é 0.025288999258926914 e o ultimo é 0.6513139108024808


# Mundo 5

Essas últimas duas aulas foram rápidas e bem simples. Nos mundos 5 e 6 nós vamos mais a fundo no numpy, descobrindo como podemos fazer conta, extrair
estatísticas, juntar arrays, rankear arrays, adicionar e excluir dados e muito mais. No mundo 5 descobrir como manipular esses arrays da melhor forma!